-- 0075_blog_posts.sql
--
-- Programmatic SEO blog. The cron at workers/blog-publish/ fires daily
-- at 09:00 UTC, rolls a 50% skip (so cadence averages ~every 2 days
-- and avoids a fixed-interval bot footprint), picks a real-estate
-- marketing topic from src/lib/blog/topic-pool.ts, generates an HTML
-- article via Anthropic, and inserts a row here. Public pages at
-- /[locale]/blog/[slug] render the row.
--
-- One row = one published article. Multi-language strategy: v1 ships
-- English only (no fallback into other locales; the post just doesn't
-- exist there until a translator pass). Hreflang signals the absence
-- so search engines don't see a thin/duplicate page.
--
-- RLS model:
--   - SELECT: anyone (it's a published article; visibility gated by
--     `status = 'published'` in the public-page query).
--   - INSERT / UPDATE / DELETE: service-role only (cron writes; admin
--     UI for moderation is a future surface, not v1).
--
-- Indexes:
--   - (status, published_at desc) → blog index page sort
--   - unique (slug) → URL stability + dedupe defense
--   - (topic_key) → "have we already covered this topic" lookup the
--     cron uses to dedupe before generating

create table public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  -- URL-safe identifier — used in /blog/<slug>. Generated from the
  -- topic + a short hash so two articles on the same topic don't
  -- collide. Unique-indexed below.
  slug text not null,
  -- Topic-key (the topic-pool entry's stable id, not the title) is
  -- separate from the title so we can dedupe at the topic level
  -- while letting different angles of the same topic ship under
  -- different slugs over time.
  topic_key text not null,
  language text not null default 'en' check (language in ('en', 'es', 'pl', 'pt', 'de', 'fr', 'it')),
  -- Editorial fields generated by the AI + post-processed.
  title text not null,
  -- One-sentence summary used in <meta description> + the index card.
  summary text not null,
  -- The full HTML body emitted by the AI generator and run through
  -- the in-process sanitizer (strips Microdata, validates anchor
  -- targets, ensures <nav> / breadcrumb / ToC / author bio / review
  -- line are all present per the tech-spec contract).
  body_html text not null,
  -- Hero image url + optional srcset descriptor JSON. NULL = no hero
  -- image (the page-render path then renders a CSS background only).
  hero_image_url text,
  hero_image_srcset jsonb,
  -- Editorial signals — written into the page + into JSON-LD Article
  -- as `author` and `reviewedBy`. Both are stamped at publish time
  -- using the constants in src/lib/blog/author.ts; the columns are
  -- here for forward-compat (multi-author CMS in a future life).
  author_name text not null,
  author_role text not null,
  author_url text,
  reviewer_name text,
  reviewed_at timestamptz,
  -- The pricing / engagement gates from the generator. word_count
  -- powers reading-time estimates rendered above the article body.
  word_count integer not null default 0,
  -- Lifecycle. draft → ai_failed → review → published → archived.
  -- v1 cron writes directly into 'published' on a successful generate
  -- (no human review gate); 'ai_failed' rows hold the diagnostic so
  -- the failure email + future admin UI can show "why".
  status text not null default 'draft' check (status in (
    'draft', 'ai_failed', 'review', 'published', 'archived'
  )),
  -- Failure diagnostic when status='ai_failed'. Free-form; the cron
  -- writes the categorized error code from the generator
  -- (no_response, html_invalid, missing_toc, missing_breadcrumb,
  -- microdata_present, anthropic_<code>).
  failure_reason text,
  -- The model + token usage so /admin/audit-costs can attribute blog
  -- generation cost alongside Free Audit + listing draft cost. Mirror
  -- of the columns on `ai_audits` so admin queries don't need a join.
  model text,
  input_tokens integer,
  output_tokens integer,
  estimated_cost_usd_cents integer,
  -- Distribution log — JSONB so we can record cross-posts to
  -- Facebook / Instagram / LinkedIn / etc as they happen. Each entry:
  --   { channel: 'facebook'|'instagram'|'linkedin', status: 'queued'|'posted'|'failed',
  --     external_id?: string, error?: string, at: iso8601 }
  distribution jsonb not null default '[]'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index uq_blog_posts_slug on public.blog_posts(slug);
create index idx_blog_posts_status_published on public.blog_posts(status, published_at desc)
  where status = 'published';
create index idx_blog_posts_topic_key on public.blog_posts(topic_key, created_at desc);

alter table public.blog_posts enable row level security;

-- Public read on published rows only. Drafts + ai_failed + archived
-- stay invisible. The public page query also adds an explicit
-- status='published' filter as defense in depth, but the RLS keeps
-- non-published rows out of any anon scan.
create policy "anon_read_published_blog_posts" on public.blog_posts
  for select to anon, authenticated
  using (status = 'published');

-- Service-role bypasses RLS implicitly, so no INSERT/UPDATE policies.
-- Per the migration-0065 hygiene convention, REVOKE write grants
-- defensively even though no policy lets them through.
revoke insert, update, delete on public.blog_posts from anon, authenticated;

create trigger blog_posts_set_updated_at
  before update on public.blog_posts
  for each row execute function public.touch_updated_at();

comment on table public.blog_posts is
  'Programmatic SEO blog. One row per published article. Populated by workers/blog-publish (50% jitter cron at 09:00 UTC, ~every 2 days). Public /[locale]/blog/[slug] pages read from here.';
